---
- name: "configuration play."
  hosts: web
  user: dcerag
  gather_facts: false
  vars:
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
    - ansible_port: '56024'

  pre_tasks:
    - setup:
  roles:
    - configure-server
