---
- name: "configuration play."
  hosts: devapp01
  user: dcerag
  gather_facts: false
  vars:
      - ansible_python_interpreter: /usr/bin/python3
      - ansible_host_key_checking: false
      - ansible_stdout_callback: yaml
      - ansible_port: '56024'
      - ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  pre_tasks:
      - setup:
      - name: "install python for Ansible."
        become: true
        raw: test -e /usr/bin/python3 || (apt -y update && apt install -y python3)
        changed_when: false
      - name: "Install rsync for Ansible."
        connection: local
        package:
            name: rsync
            state: present
  roles:
      - configure-server
      - deploy-code
