---
- name: "configuration play."
  hosts: devapp01
  user: dcerag
  gather_facts: false
  vars:
      - ansible_host_key_checking: false
      - ansible_stdout_callback: yaml
      - ansible_port: '56024'
      - ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  pre_tasks:
      - name: install rsync on the ansible controller
        connection: local
        package:
          name: rsync
          state: present
      - setup:
  roles:
      - configure-server
      - deploy-code
