---
- name: "configuration play."
  hosts: devapp01
  user: dcerag
  become: yes
  become_user: dcerag
  gather_facts: true
  vars:
      - ansible_host_key_checking: false
      - ansible_stdout_callback: yaml
      - ansible_port: '56024'
      - ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  pre_tasks:
      - setup:
  roles:
      - configure-server
      - deploy-code
