---
- name: "configuration play."
  hosts: devapp01
  user: dcerag
  gather_facts: false
  vars:
      - ansible_host_key_checking: false
      - ansible_stdout_callback: yaml
      - ansible_python_interpreter: /usr/local/bin/python3.6
      - ansible_port: '56024'
      - ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  pre_tasks:
      - setup:
      - name: "Install rsync for Ansible."
        connection: local
        become: true
        package:
            name: rsync
            state: present
  roles:
      - configure-server
      - deploy-code
