---
- name: "install dependencies."
  become: true
  yum:
    name: ["nodejs14"]
    state: latest
    update_cache: false

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
