---
- name: "Install rsync."
  become: true
  dnf:
    name: ["rsync"]
    state: latest

- name: "Install python."
  become: true
  dnf:
    name: ["python", "python3"]
    state: latest

- name: "Install nodejs."
  become: true
  dnf:
    name: ["@nodejs:14"]
    state: latest

- name: "Install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
