---
- name: "Set Docker repository."
  become: true
  shell: |
      yum-config-manager –add-repo https://download.docker.com/linux/centos/docker-ce.repo
      exit 0

- name: "Install OS dependencies."
  become: true
  yum:
    name: ["yum-utils"]
    state: latest

- name: "Install nodejs."
  become: true
  dnf:
    name: ["@nodejs:14"]
    state: latest

- name: "Install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
