- name: Copying files from CircleCI to VM
  copy:
      src: /root/project/
      dest: /home/dcerag/app/web

- name: Install node dependencies
  shell: |
      cd /home/dcerag/app/web/server
      npm install

- name: Start PM2
  become: true
  shell: |
      cd /home/dcerag/app/web/server
      /usr/local/bin/pm2 ls start --name lsm-node npm  -- run start:prod