- name: Copying files from CircleCI to VM
  copy:
      src: /root/project/
      dest: /home/dcerag/app/web

- name: Install node dependencies
  shell: |
      cd /home/dcerag/app/web/server
      npm install

- name: Stop PM2
  ignore_errors: yes
  shell: |
      cd /home/ubuntu/backend
      sudo /usr/local/bin/pm2 stop lsm-node
      sudo /usr/local/bin/pm2 delete lsm-node

- name: Start PM2
  become: true
  shell: |
      cd /home/dcerag/app/web/server
      sudo /usr/local/bin/pm2 start --name "lsm-node" npm -- run start:prod