- name: Copying files from CircleCI to VM
  copy:
      src: /root/project/
      dest: /home/dcerag/app/web
      recursive: yes

- name: Install node dependencies
  shell: |
      cd /home/dcerag/app/web/server
      npm install