- name: Testing folders
  shell: |
      pwd
      touch test.txt
      ls -la >> test.txt

- name: Copying files from CircleCI to VM
  copy:
      src: /project
      remote_src: true
      dest: /home/dcerag/app