version: 2.1
orbs:
    node: circleci/node@4.2.0

jobs:
    build-frontend:
        working_directory: "~/project"
        executor:
            name: node/default
            tag: "14.16.1"
        steps:
            - checkout
            - run:
                  name: Create `.npmrc` file
                  working_directory: client
                  command: |
                      touch .npmrc
                      echo //npm.fontawesome.com/:_authToken=${FA_KEY} >> .npmrc
                      echo @fortawesome:registry=https://npm.fontawesome.com/ >> .npmrc
                      echo /npm.greensock.com/:_authToken=${GS_KEY} >> .npmrc
                      echo @gsap:registry=https://npm.greensock.com >> .npmrc
            - node/install-packages:
                  app-dir: "~/project/client"
                  override-ci-command: npm install
                  cache-version: v3
            - run:
                  name: Audit frontend packages
                  working_directory: client
                  command: npm audit
            - run:
                  name: Test frontend code
                  working_directory: client
                  command: npm test
            - run:
                  name: Build frontend modules
                  working_directory: client
                  command: |
                    if [ "${CIRCLE_BRANCH}" == "master" ]; then
                      npm run build:all:prod
                    else
                      npm run build:all
                    fi

            - run:
                  name: Destroy `etc` and `node_modules` folder
                  working_directory: client
                  command: |
                      rm .npmrc
                      rm _etc -r
                      rm node_modules -rf
            - run:
                  name: Destroy `src` folders
                  working_directory: client
                  command: rm **/src -rf
            - persist_to_workspace:
                  root: ~/project
                  paths:
                      - client
                      - .circleci

    build-backend:
        working_directory: "~/project"
        executor:
            name: node/default
            tag: "14.16.1"
        steps:
            - checkout
            - run:
                  name: Attach backend environment variables
                  working_directory: server
                  command: |
                      echo DB2_DB=$DB2_DB >> ".env"
                      echo DB2_HOST=$DB2_HOST >> ".env"
                      echo DB2_PORT=$DB2_PORT >> ".env"
                      echo DB2_UID=$DB2_UID >> ".env"
                      echo DB2_PASSWORD=$DB2_PASSWORD >> ".env"
                      echo DB2_SCHEMA=$DB2_SCHEMA >> ".env"
                      if [ "${CIRCLE_BRANCH}" == "master" ]; then
                        echo NODE_ENV=production >> ".env"
                      else
                        echo NODE_ENV=development >> ".env"
                      fi
            - node/install-packages:
                  app-dir: "~/project/server"
                  override-ci-command: npm install
            - run:
                  name: Audit backend packages
                  working_directory: server
                  command: npm audit
            - run:
                  name: Test backend code
                  working_directory: server
                  command: npm test
            - run:
                  name: Destroy `node_modules` folder
                  working_directory: server
                  command: rm node_modules -rf
            -  persist_to_workspace:
                   root: ~/project
                   paths:
                       - server

    deploy-app:
        working_directory: ~/project
        docker:
            -  image: python:3.7-alpine3.11
        shell: /bin/sh -leo pipefail
        environment:
            - BASH_ENV: /etc/profile
        steps:
            - attach_workspace:
                  at: ~/project
            - add_ssh_keys:
                  fingerprints: [ "e2:1c:76:aa:29:61:db:ca:a1:d3:c2:59:c6:0c:b1:b9" ]
            - run:
                  name: Update and upgrade packages
                  command: |
                      apk update
                      apk upgrade
                      apk add --update ansible openssh rsync
            - deploy:
                  name: Deploy the application
                  no_output_timeout: 30m
                  command: |
                      apk add --update ansible
                      cd .circleci/ansible
                      ansible-playbook -i inventory.txt playbook.yml

workflows:
    test_my_app:
        jobs:
            - build-frontend
            - build-backend
            - deploy-app:
                  filters:
                      branches:
                          only: master
                  requires:
                      - build-frontend
                      - build-backend
