---
- name: "Update npm."
  become: true
  npm:
      name: npm
      global: yes
      state: latest

- name: "Install pm2."
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "Install node dependencies."
  shell: |
      cd /app/lsm/web/server
      npm install

- name: "Stop PM2."
  ignore_errors: yes
  shell: |
      cd /home/ubuntu/backend
      pm2 stop lsm-node
      pm2 delete lsm-node

- name: "Start PM2."
  shell: |
      cd /app/lsm/web/server
      pm2 start --name "lsm-node" npm -- run start:prod